name: Deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          key: ${{ secrets.LINODE_SSHKEY }}
          port: ${{ secrets.LINODE_PORT }}
          password: ""
          script: |
            cd openmapsbh;git stash; git pull;npm install;shadow-cljs release release;cp -TR public/ /var/www/openmaps/
      - name: Purge cache
        uses: jakejarvis/cloudflare-purge-action@master
        env:
        # Zone is required by both authentication methods
          CLOUDFLARE_ZONE: ${{ secrets.CLOUDFLARE_ZONE }}
          CLOUDFLARE_TOKEN: ${{ secrets.CLOUDFLARE_TOKEN }}
